// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAJ_RYL8Kc_9ngY86AVQ6UoX8wAjECdvg',
    appId: '1:349653941276:web:6f425aaf5e1e321ce273d9',
    messagingSenderId: '349653941276',
    projectId: 'influencers-8d4e4',
    authDomain: 'influencers-8d4e4.firebaseapp.com',
    storageBucket: 'influencers-8d4e4.appspot.com',
    measurementId: 'G-PLKPQNL7PG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxj1RAbP1dbP4UMnAmP78gvxTU1gJDnco',
    appId: '1:349653941276:android:42dd3c92400dbae9e273d9',
    messagingSenderId: '349653941276',
    projectId: 'influencers-8d4e4',
    storageBucket: 'influencers-8d4e4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZy3dQdalsLNSx_TrUKU42CReyR3PQ_LM',
    appId: '1:349653941276:ios:05dcc735c3e21ce7e273d9',
    messagingSenderId: '349653941276',
    projectId: 'influencers-8d4e4',
    storageBucket: 'influencers-8d4e4.appspot.com',
    iosBundleId: 'com.example.influencer',
  );
}
